// HP Landscaping - San Diego County Service Areas and Services

export const LOGO_URL = "https://storage.googleapis.com/msgsndr/T5QQu0Akcy942Ox0QIk7/media/67e5bda482c9d83767bffe13.png";

export const COMPANY_INFO = {
  name: "HP Landscaping",
  tagline: "Professional Landscaping Services in San Diego County",
  phone: "(619) 935-3965",
  email: "info@hplandscapingmaintenance.com",
  website: "https://www.hplandscapingmaintenance.com",
  domain: "hplandscapingmaintenance.com",
  address: "San Diego, CA",
  hours: "Mon-Sat: 7AM - 6PM",
  foundedYear: 2000,
  licenseNumber: "CA-LIC-123456",
};

export const SERVICES = [
  {
    id: "landscape-design",
    name: "Landscape Design",
    shortDescription: "Custom landscape designs tailored to San Diego's climate",
    description: "Transform your outdoor space with our expert landscape design services. We create stunning, sustainable designs that complement San Diego's Mediterranean climate while maximizing your property's potential.",
    icon: "Palette",
    features: [
      "3D Design Visualization",
      "Drought-Tolerant Planning",
      "Hardscape Integration",
      "Native Plant Selection",
      "Lighting Design",
      "Water Feature Design",
    ],
    image: "/images/services/landscape-design.jpg",
  },
  {
    id: "irrigation-systems",
    name: "Irrigation Systems",
    shortDescription: "Smart irrigation solutions for water efficiency",
    description: "Save water and money with our professional irrigation system installation and repair services. We specialize in smart irrigation technology that keeps your landscape healthy while conserving San Diego's precious water resources.",
    icon: "Droplets",
    features: [
      "Smart Controller Installation",
      "Drip Irrigation Systems",
      "Sprinkler System Design",
      "Leak Detection & Repair",
      "Water Audit Services",
      "Rain Sensor Integration",
    ],
    image: "/images/services/irrigation.jpg",
  },
  {
    id: "hardscaping",
    name: "Hardscaping",
    shortDescription: "Patios, walkways, retaining walls, and more",
    description: "Enhance your outdoor living space with beautiful hardscape features. From elegant patios to functional retaining walls, we build lasting structures that add value and beauty to your San Diego property.",
    icon: "Layers",
    features: [
      "Paver Patios & Walkways",
      "Retaining Walls",
      "Outdoor Kitchens",
      "Fire Pits & Fireplaces",
      "Pergolas & Arbors",
      "Decorative Concrete",
    ],
    image: "/images/services/hardscaping.jpg",
  },
  {
    id: "lawn-care",
    name: "Lawn Care & Maintenance",
    shortDescription: "Keep your lawn healthy and beautiful year-round",
    description: "Our comprehensive lawn care services keep your San Diego lawn looking its best throughout the year. From regular maintenance to specialized treatments, we've got your lawn covered.",
    icon: "Scissors",
    features: [
      "Weekly Mowing Service",
      "Fertilization Programs",
      "Weed Control",
      "Aeration & Overseeding",
      "Pest Management",
      "Seasonal Clean-ups",
    ],
    image: "/images/services/lawn-care.jpg",
  },
  {
    id: "tree-services",
    name: "Tree Services",
    shortDescription: "Professional tree care and maintenance",
    description: "Protect your property and enhance your landscape with our professional tree services. Our certified arborists provide expert care for trees of all sizes throughout San Diego County.",
    icon: "TreePine",
    features: [
      "Tree Trimming & Pruning",
      "Tree Removal",
      "Stump Grinding",
      "Tree Health Assessment",
      "Palm Tree Maintenance",
      "Emergency Tree Service",
    ],
    image: "/images/services/tree-services.jpg",
  },
  {
    id: "outdoor-lighting",
    name: "Outdoor Lighting",
    shortDescription: "Illuminate your landscape with professional lighting",
    description: "Extend your outdoor enjoyment into the evening hours with our professional landscape lighting services. We design and install lighting systems that enhance beauty, safety, and security.",
    icon: "Lightbulb",
    features: [
      "Path & Walkway Lighting",
      "Accent Lighting",
      "Security Lighting",
      "LED Upgrades",
      "Smart Lighting Controls",
      "Holiday Lighting",
    ],
    image: "/images/services/outdoor-lighting.jpg",
  },
  {
    id: "water-features",
    name: "Water Walls & Waterfalls",
    shortDescription: "Stunning water features to transform your outdoor space",
    description: "Create a tranquil paradise with our custom water wall and waterfall installations. From modern water walls to natural rock waterfalls, we design and build breathtaking water features that add movement, sound, and serenity to your San Diego landscape.",
    icon: "Waves",
    features: [
      "Custom Water Walls",
      "Natural Rock Waterfalls",
      "Pond & Stream Design",
      "Fountain Installation",
      "Koi Pond Construction",
      "Water Feature Lighting",
    ],
    image: "/images/services/water-features.jpg",
  },
];

export const SERVICE_AREAS = [
  {
    id: "san-diego",
    name: "San Diego",
    county: "San Diego County",
    description: "Serving all neighborhoods in San Diego including Downtown, La Jolla, Pacific Beach, Mission Valley, and more.",
    population: "1.4M+",
    featured: true,
    image: "/images/areas/san-diego.jpg",
  },
  {
    id: "chula-vista",
    name: "Chula Vista",
    county: "San Diego County",
    description: "Professional landscaping services throughout Chula Vista, from Eastlake to Otay Ranch.",
    population: "275K+",
    featured: true,
    image: "/images/areas/chula-vista.jpg",
  },
  {
    id: "oceanside",
    name: "Oceanside",
    county: "San Diego County",
    description: "Coastal landscaping expertise for Oceanside residents and businesses.",
    population: "176K+",
    featured: true,
    image: "/images/areas/oceanside.jpg",
  },
  {
    id: "escondido",
    name: "Escondido",
    county: "San Diego County",
    description: "Serving Escondido with drought-tolerant landscaping solutions.",
    population: "151K+",
    featured: true,
    image: "/images/areas/escondido.jpg",
  },
  {
    id: "carlsbad",
    name: "Carlsbad",
    county: "San Diego County",
    description: "Premium landscaping services for Carlsbad's beautiful communities.",
    population: "114K+",
    featured: true,
    image: "/images/areas/carlsbad.jpg",
  },
  {
    id: "el-cajon",
    name: "El Cajon",
    county: "San Diego County",
    description: "Expert landscaping tailored to El Cajon's unique climate.",
    population: "106K+",
    featured: false,
    image: "/images/areas/el-cajon.jpg",
  },
  {
    id: "vista",
    name: "Vista",
    county: "San Diego County",
    description: "Full-service landscaping for Vista homeowners and businesses.",
    population: "101K+",
    featured: false,
    image: "/images/areas/vista.jpg",
  },
  {
    id: "san-marcos",
    name: "San Marcos",
    county: "San Diego County",
    description: "Comprehensive landscaping services throughout San Marcos.",
    population: "97K+",
    featured: false,
    image: "/images/areas/san-marcos.jpg",
  },
  {
    id: "encinitas",
    name: "Encinitas",
    county: "San Diego County",
    description: "Coastal and inland landscaping expertise for Encinitas.",
    population: "63K+",
    featured: false,
    image: "/images/areas/encinitas.jpg",
  },
  {
    id: "national-city",
    name: "National City",
    county: "San Diego County",
    description: "Affordable landscaping solutions for National City.",
    population: "61K+",
    featured: false,
    image: "/images/areas/national-city.jpg",
  },
  {
    id: "la-mesa",
    name: "La Mesa",
    county: "San Diego County",
    description: "Beautiful landscaping services for the Jewel of the Hills.",
    population: "60K+",
    featured: false,
    image: "/images/areas/la-mesa.jpg",
  },
  {
    id: "santee",
    name: "Santee",
    county: "San Diego County",
    description: "Residential and commercial landscaping in Santee.",
    population: "58K+",
    featured: false,
    image: "/images/areas/santee.jpg",
  },
  {
    id: "poway",
    name: "Poway",
    county: "San Diego County",
    description: "Premium landscaping for Poway's upscale communities.",
    population: "49K+",
    featured: false,
    image: "/images/areas/poway.jpg",
  },
  {
    id: "del-mar",
    name: "Del Mar",
    county: "San Diego County",
    description: "Luxury landscaping services for Del Mar estates.",
    population: "4K+",
    featured: false,
    image: "/images/areas/del-mar.jpg",
  },
  {
    id: "coronado",
    name: "Coronado",
    county: "San Diego County",
    description: "Island landscaping specialists serving Coronado.",
    population: "24K+",
    featured: false,
    image: "/images/areas/coronado.jpg",
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Sarah M.",
    location: "La Jolla, San Diego",
    rating: 5,
    text: "HP Landscaping transformed our backyard into a beautiful oasis. Their attention to detail and knowledge of drought-tolerant plants is impressive!",
    service: "Landscape Design",
  },
  {
    id: 2,
    name: "Michael R.",
    location: "Carlsbad",
    rating: 5,
    text: "Professional, punctual, and excellent work. Our new irrigation system has already reduced our water bill significantly.",
    service: "Irrigation Systems",
  },
  {
    id: 3,
    name: "Jennifer L.",
    location: "Chula Vista",
    rating: 5,
    text: "The team installed a beautiful paver patio and fire pit. We now spend every evening outside enjoying our new outdoor living space.",
    service: "Hardscaping",
  },
  {
    id: 4,
    name: "David K.",
    location: "Escondido",
    rating: 5,
    text: "Reliable weekly lawn service that keeps our property looking immaculate. Highly recommend their maintenance programs!",
    service: "Lawn Care",
  },
];

export const STATS = [
  { value: "15+", label: "Years Experience" },
  { value: "5000+", label: "Projects Completed" },
  { value: "98%", label: "Customer Satisfaction" },
  { value: "50+", label: "Team Members" },
];

export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/services", label: "Services" },
  { href: "/areas", label: "Service Areas" },
  { href: "/gallery", label: "Gallery" },
  { href: "/about", label: "About" },
  { href: "/contact", label: "Contact" },
];
