// HP Landscaping - San Diego County Service Areas and Services

export const LOGO_URL = "https://storage.googleapis.com/msgsndr/T5QQu0Akcy942Ox0QIk7/media/67e5bda482c9d83767bffe13.png";

export const COMPANY_INFO = {
  name: "HP Landscaping",
  tagline: "SLA-Backed Commercial Landscaping for San Diego Businesses",
  phone: "(619) 935-3965",
  email: "info@hplandscapingmaintenance.com",
  website: "https://www.hplandscapingmaintenance.com",
  domain: "hplandscapingmaintenance.com",
  address: "San Diego, CA",
  hours: "Mon-Sat: 7AM - 6PM",
  foundedYear: 2000,
  licenseNumber: "CA-LIC-123456",
  valueProposition: "We become your landscaping department—scheduled, reliable, guaranteed.",
};

export const SERVICES = [
  {
    id: "landscape-design",
    name: "Landscape Design",
    shortDescription: "Custom landscape designs tailored to San Diego's climate",
    description: "Transform your outdoor space with our expert landscape design services. We create stunning, sustainable designs that complement San Diego's Mediterranean climate while maximizing your property's potential.",
    icon: "Palette",
    features: [
      "3D Design Visualization",
      "Drought-Tolerant Planning",
      "Hardscape Integration",
      "Native Plant Selection",
      "Lighting Design",
      "Water Feature Design",
    ],
    image: "/images/services/landscape-design.jpg",
  },
  {
    id: "irrigation-systems",
    name: "Irrigation Systems",
    shortDescription: "Smart irrigation solutions for water efficiency",
    description: "Save water and money with our professional irrigation system installation and repair services. We specialize in smart irrigation technology that keeps your landscape healthy while conserving San Diego's precious water resources.",
    icon: "Droplets",
    features: [
      "Smart Controller Installation",
      "Drip Irrigation Systems",
      "Sprinkler System Design",
      "Leak Detection & Repair",
      "Water Audit Services",
      "Rain Sensor Integration",
    ],
    image: "/images/services/irrigation.jpg",
  },
  {
    id: "hardscaping",
    name: "Hardscaping",
    shortDescription: "Patios, walkways, retaining walls, and more",
    description: "Enhance your outdoor living space with beautiful hardscape features. From elegant patios to functional retaining walls, we build lasting structures that add value and beauty to your San Diego property.",
    icon: "Layers",
    features: [
      "Paver Patios & Walkways",
      "Retaining Walls",
      "Outdoor Kitchens",
      "Fire Pits & Fireplaces",
      "Pergolas & Arbors",
      "Decorative Concrete",
    ],
    image: "/images/services/hardscaping.jpg",
  },
  {
    id: "lawn-care",
    name: "Lawn Care & Maintenance",
    shortDescription: "Keep your lawn healthy and beautiful year-round",
    description: "Our comprehensive lawn care services keep your San Diego lawn looking its best throughout the year. From regular maintenance to specialized treatments, we've got your lawn covered.",
    icon: "Scissors",
    features: [
      "Weekly Mowing Service",
      "Fertilization Programs",
      "Weed Control",
      "Aeration & Overseeding",
      "Pest Management",
      "Seasonal Clean-ups",
    ],
    image: "/images/services/lawn-care.jpg",
  },
  {
    id: "tree-services",
    name: "Tree Services",
    shortDescription: "Professional tree care and maintenance",
    description: "Protect your property and enhance your landscape with our professional tree services. Our certified arborists provide expert care for trees of all sizes throughout San Diego County.",
    icon: "TreePine",
    features: [
      "Tree Trimming & Pruning",
      "Tree Removal",
      "Stump Grinding",
      "Tree Health Assessment",
      "Palm Tree Maintenance",
      "Emergency Tree Service",
    ],
    image: "/images/services/tree-services.jpg",
  },
  {
    id: "outdoor-lighting",
    name: "Outdoor Lighting",
    shortDescription: "Illuminate your landscape with professional lighting",
    description: "Extend your outdoor enjoyment into the evening hours with our professional landscape lighting services. We design and install lighting systems that enhance beauty, safety, and security.",
    icon: "Lightbulb",
    features: [
      "Path & Walkway Lighting",
      "Accent Lighting",
      "Security Lighting",
      "LED Upgrades",
      "Smart Lighting Controls",
      "Holiday Lighting",
    ],
    image: "/images/services/outdoor-lighting.jpg",
  },
  {
    id: "water-features",
    name: "Water Walls & Waterfalls",
    shortDescription: "Stunning water features to transform your outdoor space",
    description: "Create a tranquil paradise with our custom water wall and waterfall installations. From modern water walls to natural rock waterfalls, we design and build breathtaking water features that add movement, sound, and serenity to your San Diego landscape.",
    icon: "Waves",
    features: [
      "Custom Water Walls",
      "Natural Rock Waterfalls",
      "Pond & Stream Design",
      "Fountain Installation",
      "Koi Pond Construction",
      "Water Feature Lighting",
    ],
    image: "/images/services/water-features.jpg",
  },
];

export const SERVICE_AREAS = [
  {
    id: "san-diego",
    name: "San Diego",
    county: "San Diego County",
    description: "Serving all neighborhoods in San Diego including Downtown, La Jolla, Pacific Beach, Mission Valley, and more.",
    population: "1.4M+",
    featured: true,
    image: "/images/areas/san-diego.jpg",
  },
  {
    id: "chula-vista",
    name: "Chula Vista",
    county: "San Diego County",
    description: "Professional landscaping services throughout Chula Vista, from Eastlake to Otay Ranch.",
    population: "275K+",
    featured: true,
    image: "/images/areas/chula-vista.jpg",
  },
  {
    id: "oceanside",
    name: "Oceanside",
    county: "San Diego County",
    description: "Coastal landscaping expertise for Oceanside residents and businesses.",
    population: "176K+",
    featured: true,
    image: "/images/areas/oceanside.jpg",
  },
  {
    id: "escondido",
    name: "Escondido",
    county: "San Diego County",
    description: "Serving Escondido with drought-tolerant landscaping solutions.",
    population: "151K+",
    featured: true,
    image: "/images/areas/escondido.jpg",
  },
  {
    id: "carlsbad",
    name: "Carlsbad",
    county: "San Diego County",
    description: "Premium landscaping services for Carlsbad's beautiful communities.",
    population: "114K+",
    featured: true,
    image: "/images/areas/carlsbad.jpg",
  },
  {
    id: "el-cajon",
    name: "El Cajon",
    county: "San Diego County",
    description: "Expert landscaping tailored to El Cajon's unique climate.",
    population: "106K+",
    featured: false,
    image: "/images/areas/el-cajon.jpg",
  },
  {
    id: "vista",
    name: "Vista",
    county: "San Diego County",
    description: "Full-service landscaping for Vista homeowners and businesses.",
    population: "101K+",
    featured: false,
    image: "/images/areas/vista.jpg",
  },
  {
    id: "san-marcos",
    name: "San Marcos",
    county: "San Diego County",
    description: "Comprehensive landscaping services throughout San Marcos.",
    population: "97K+",
    featured: false,
    image: "/images/areas/san-marcos.jpg",
  },
  {
    id: "encinitas",
    name: "Encinitas",
    county: "San Diego County",
    description: "Coastal and inland landscaping expertise for Encinitas.",
    population: "63K+",
    featured: false,
    image: "/images/areas/encinitas.jpg",
  },
  {
    id: "national-city",
    name: "National City",
    county: "San Diego County",
    description: "Affordable landscaping solutions for National City.",
    population: "61K+",
    featured: false,
    image: "/images/areas/national-city.jpg",
  },
  {
    id: "la-mesa",
    name: "La Mesa",
    county: "San Diego County",
    description: "Beautiful landscaping services for the Jewel of the Hills.",
    population: "60K+",
    featured: false,
    image: "/images/areas/la-mesa.jpg",
  },
  {
    id: "santee",
    name: "Santee",
    county: "San Diego County",
    description: "Residential and commercial landscaping in Santee.",
    population: "58K+",
    featured: false,
    image: "/images/areas/santee.jpg",
  },
  {
    id: "poway",
    name: "Poway",
    county: "San Diego County",
    description: "Premium landscaping for Poway's upscale communities.",
    population: "49K+",
    featured: false,
    image: "/images/areas/poway.jpg",
  },
  {
    id: "del-mar",
    name: "Del Mar",
    county: "San Diego County",
    description: "Luxury landscaping services for Del Mar estates.",
    population: "4K+",
    featured: false,
    image: "/images/areas/del-mar.jpg",
  },
  {
    id: "coronado",
    name: "Coronado",
    county: "San Diego County",
    description: "Island landscaping specialists serving Coronado.",
    population: "24K+",
    featured: false,
    image: "/images/areas/coronado.jpg",
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Sarah M.",
    location: "Property Manager, La Jolla",
    rating: 5,
    text: "I haven't thought about landscaping in 6 months. HP handles everything across my 12 properties. That's easily 5-6 hours a month I've gotten back.",
    service: "Commercial Maintenance",
    timeSaved: "5-6 hours/month",
  },
  {
    id: 2,
    name: "Michael R.",
    location: "HOA Board President, Carlsbad",
    rating: 5,
    text: "Zero tenant complaints since switching to HP. Their SLA guarantee isn't just marketing—they actually show up when they say they will.",
    service: "HOA Contract",
    timeSaved: "4 hours/month",
  },
  {
    id: 3,
    name: "Jennifer L.",
    location: "Facilities Director, Chula Vista",
    rating: 5,
    text: "The dedicated account manager is a game-changer. One point of contact for our entire office park. No more chasing vendors.",
    service: "Commercial Contract",
    timeSaved: "8 hours/month",
  },
  {
    id: 4,
    name: "David K.",
    location: "Property Management Firm, Escondido",
    rating: 5,
    text: "We've tried 4 landscaping companies in 3 years. HP is the only one that treats our portfolio like their own. Reliability is everything.",
    service: "Portfolio Management",
    timeSaved: "6 hours/month",
  },
];

export const STATS = [
  { value: "25+", label: "Years in Business" },
  { value: "50,000+", label: "On-Time Services" },
  { value: "99.4%", label: "Reliability Rate" },
  { value: "4.2 hrs", label: "Avg. Monthly Time Saved" },
];

export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/commercial", label: "Commercial" },
  { href: "/services", label: "Services" },
  { href: "/areas", label: "Service Areas" },
  { href: "/gallery", label: "Gallery" },
  { href: "/about", label: "About" },
  { href: "/contact", label: "Contact" },
];

export const COMMERCIAL_PACKAGES = [
  {
    id: "delegate",
    name: "Delegate",
    price: "$700",
    period: "/month",
    description: "For single properties and small offices",
    features: [
      "Weekly maintenance (fixed day/time)",
      "Seasonal refresh (4x/year)",
      "24-hour emergency response",
      "Service-level agreement",
      "Direct communication line",
    ],
    cta: "Start Delegating",
    popular: false,
  },
  {
    id: "replace",
    name: "Replace",
    price: "$1,200",
    period: "/month",
    description: "For 3-10 properties and HOAs",
    features: [
      "Everything in Delegate, plus:",
      "Multi-property coordination",
      "Dedicated account manager",
      "Quarterly budget planning",
      "Monthly photo reports",
      "Tenant communication handling",
    ],
    cta: "Replace Your Headaches",
    popular: true,
  },
  {
    id: "invest",
    name: "Invest",
    price: "$2,500",
    period: "/month",
    description: "For large portfolios and property management firms",
    features: [
      "Everything in Replace, plus:",
      "Tenant satisfaction surveys",
      "2-hour priority emergency response",
      "Annual master planning",
      "Custom reporting dashboard",
      "Preferred vendor status",
    ],
    cta: "Invest in Peace of Mind",
    popular: false,
  },
];

export const SLA_GUARANTEE = {
  headline: "Our Guarantee: Miss a Service, Get It Free",
  description: "We put our money where our mower is.",
  terms: [
    {
      condition: "Miss a scheduled service window",
      result: "That week is free",
    },
    {
      condition: "Miss twice within 90 days",
      result: "Cancel penalty-free + we pay your first month with a replacement vendor",
    },
  ],
  footnote: "No excuses. No exceptions. That's the HP difference.",
};
